// 7 address lines on the keyboard, I have no idea if all of them are valid
#define KEYMAP_SIZE 128

// we can just pretend that this is the keymap for now, we just need a dummy untill we can figure out the keymap
// repeated key A 128 times 
#define KEYMAP {KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A,KEY_A}
